#-------------------------------
# General Site Settings
baseurl: "/journal" # the subpath of your site, e.g. /blog
url: "https://maaaxwa.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/records/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_posts'
    values:
      permalink: /records/:year/:month/:day/:title

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed